<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Aswins-Air.adactin.guest" failures="0" tests="1" name="Default test" time="2.202" errors="0" timestamp="04 Feb 2020 05:03:44 GMT">
  <testcase classname="adactin.urbest.testrunner.Verify_Login" name="@BeforeTest Prior_to_Signon" time="2.123">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at adactin.urbest.util.TestDataReader.readdata(TestDataReader.java:22)
at adactin.urbest.base.BaseClass.initBrowser(BaseClass.java:62)
at adactin.urbest.testrunner.Verify_Login.Prior_to_Signon(Verify_Login.java:44)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.TestRunner.beforeRun(TestRunner.java:529)
at org.testng.TestRunner.run(TestRunner.java:497)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @BeforeTest Prior_to_Signon -->
  <testcase classname="adactin.urbest.testrunner.Verify_Login" name="@AfterTest Close_Browser" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterTest Close_Browser -->
  <testcase classname="adactin.urbest.testrunner.Verify_Login" name="Verify_Sign_On" time="0.0">
    <skipped/>
  </testcase> <!-- Verify_Sign_On -->
</testsuite> <!-- Default test -->
